services:
  - type: web
    name: blockchain-cert-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGO_URI
        value: "mongodb+srv://University_admin:admin123@cluster0.vhre5oy.mongodb.net/certificate_verification?retryWrites=true&w=majority&appName=Cluster0"
        sync: false
      - key: JWT_SECRET
        value: "supersecretkey123"
        sync: false
      - key: JWT_EXPIRE
        value: 24h
      - key: CLIENT_URL
        value: "https://blockchain-certificate-verification.vercel.app/"
