services:
  - type: web
    name: blockchain-cert-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: "24h"
      - key: CLIENT_URL
        value: "https://blockchain-certificate-verification.vercel.app"
